apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    uid: cassandra
    access: proxy
    url: cassandra:9042
    jsonData:
      keyspace: market_data
      user: cassandra
      consistency: ONE
    secureJsonData:
      password: cassandra
    isDefault: true
